tools:
  php_sim: true
  php_analyzer:
    enabled: false
  php_pdepend:
    enabled: false

checks:
  php:
    code_rating: true
    duplication: true


build:
  dependencies:
    before:
      - 'composer --global config process-timeout 1800'
      -
        command: 'composer install --prefer-dist --no-interaction'
        environment: { COMPOSER_PROCESS_TIMEOUT: 1800 }
        idle_timeout: 1800
  project_setup:
    before:
    - 'composer --global config process-timeout 1800'
    -
      command: 'composer install --prefer-dist --no-interaction'
      environment: { COMPOSER_PROCESS_TIMEOUT: 1800 }
      idle_timeout: 1800
