tools:
  php_sim: true
  php_analyzer:
    enabled: false
  php_pdepend:
    enabled: false

checks:
  php:
    code_rating: true
    duplication: true


build:
  environment:
    before:
      - 'composer --global config process-timeout 1800'
      - 'php -r "sleep(10)";'
      -
          command: 'composer install --prefer-dist --no-interaction'
          idle_timeout: 1800

