filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true


checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php: 5.5.12
  dependencies:
    before:
    override:
      - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800 }
    after:
  project_setup:
  tests:

application:
    type: symfony2
    boot_commands: { }
