filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'

build:
  environment:
    php: 5.5.12
  dependencies:
    before:
    override:
      - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800 }
    after:
  project_setup:
  tests:

application:
    type: symfony2
    boot_commands: {  }

