tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true

checks:
  php:
    code_rating: true
    duplication: true


build:
  environment:
    php: 5.5.12
  dependencies:
    before:
      - 'composer --global config process-timeout 1800'
      - 'cp ../artifacts/composer.lock ./composer.lock'
      - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800 }
    after:
      - 'cp composer.lock ../artifacts/composer.lock'
  project_setup:
  tests:


