before_commands:
  - 'composer --global config process-timeout 1800'
  - 'test -e ../artifacts/composer.lock && cp ../artifacts/composer.lock ./composer.lock'

filter:
  excluded_paths:
    - 'vendor/*'
    - 'tests/*'
    - 'app/*'
    - 'bin/*'
    - 'library/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: false

checks:
  php:
    code_rating: true
    duplication: true

build:
  container: 'g/adamjakab/ScrutinizerSymfony2Container@master'
  environment:
    php: 5.5.12
  dependencies:
    before:
      - { command: 'composer --global config process-timeout 1800' }
      - { command: 'cp ../artifacts/composer.lock ./composer.lock', only_if: 'test -e ../artifacts/composer.lock' }
      - { command: 'composer install --prefer-source --no-interaction --verbose', idle_timeout: 1800 }
      - { command: 'cp composer.lock ../artifacts/composer.lock', only_if: 'test -e composer.lock' }
    override:
    after:
  project_setup:
  tests:


application:
    type: none
    boot_commands: {  }


