language: php

php:
  - 5.5

before_script:
  - composer selfupdate
  - composer require symfony/symfony --prefer-source
  - composer install --no-interaction --prefer-source

script:
  - phpunit -c phpunit.xml.dist --coverage-text

after_script:

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
    on_success: never
    on_failure: always
