language: php
php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --no-interaction --prefer-source

script:
  - phpunit -c phpunit.xml.dist --coverage-text

after_script:

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
    on_success: never
    on_failure: always
