language: php

php:
  - 5.5
  - hhvm

allow_failures:
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --no-interaction --prefer-source

script:
  - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover.xml

after_script:

cache:
  directories:
    - $COMPOSER_CACHE_DIR

