language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer selfupdate
  - composer install --prefer-source --no-interaction

#script:
  # - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  # - phpcs --ignore=/vendor/*,/Tests/Resources/app/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master