language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer selfupdate
  - phpenv config-add travis.php.ini
  - composer install --no-interaction --prefer-dist

script:
  - phpunit -c phpunit.xml.dist --coverage-text

after_script:

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
    on_success: never
    on_failure: always
